FROM node:20

RUN apt-get update && \
    apt-get install -y \
        texlive \
        texlive-latex-extra \
        texlive-pictures \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 9000

CMD ["node", "index.js"]
